name: Upload Assets
on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Set up environment
      run: |
        echo "Checking environment variables"
        echo "GITHUB_TOKEN: ${{ secrets.POTATO_KEY }}"
        echo "Checking Git version"
        git --version

    - name: Manual repository clone
      run: |
        echo "Cloning repository manually"
        git clone https://github.com/CyanRayyan/Potatogame.git
        cd Potatogame
        echo "Repository cloned"
        ls -l

    - name: Set up Git user
      run: |
        cd Potatogame
        echo "Setting up Git user"
        git config --global user.name "CyanRayyan"
        if [ $? -ne 0 ]; then
          echo "Failed to set Git user name"
          exit 1
        fi
        git config --global user.email "1dangmax@hdsb.ca"
        if [ $? -ne 0 ]; then
          echo "Failed to set Git user email"
          exit 1
        fi
        echo "Git user set up completed"

    - name: Create assets directory
      run: |
        cd Potatogame
        echo "Creating assets directory"
        mkdir -p assets
        if [ $? -ne 0 ]; then
          echo "Failed to create assets directory"
          exit 1
        fi
        ls -l
        echo "Assets directory created"

    - name: Download assets
      run: |
        cd Potatogame
        echo "Downloading assets"
        wget -O assets/assets.zip "https://www.dropbox.com/scl/fi/fbuiy99tb218akvy6u9bg/Potato-By-Tyler-Dang.zip?rlkey=1wtfely7oyutriq9qqmihx64b&st=cm1smtvn&dl=1"
        if [ $? -ne 0 ]; then
          echo "Failed to download assets"
          exit 1
        fi
        echo "Assets downloaded"

    - name: Extract assets
      run: |
        cd Potatogame
        echo "Extracting assets"
        unzip assets/assets.zip -d assets
        if [ $? -ne 0 ]; then
          echo "Failed to unzip assets"
          exit 1
        fi
        ls -l assets
        echo "Assets extracted"

    - name: Debug directory structure
      run: |
        cd Potatogame
        echo "Current directory structure:"
        ls -R

    - name: Check Git status
      run: |
        cd Potatogame
        echo "Checking Git status"
        git status
        if [ $? -ne 0 ]; then
          echo "Failed to check Git status"
          exit 1
        fi

    - name: Commit and push assets
      env:
        GITHUB_TOKEN: ${{ secrets.POTATO_KEY }}
      run: |
        cd Potatogame
        echo "Starting Git operations"
        git add .
        if [ $? -ne 0 ]; then
          echo "Failed to add files to Git"
          exit 1
        fi
        git status
        git commit -m "Add assets"
        if [ $? -ne 0 ]; then
          echo "No changes to commit"
          exit 0
        fi
        git push
        if [ $? -ne 0 ]; then
          echo "Push failed"
          exit 1
        fi
        echo "Git operations completed"
