name: Upload Assets
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      continue-on-error: true  # Allow workflow to continue even if this step fails

    - name: Set up Git user
      run: |
        echo "Setting up Git user"
        git config --global user.name "CyanRayyan" || { echo "Failed to set Git user name"; exit 1; }
        git config --global user.email "1dangmax@hdsb.ca" || { echo "Failed to set Git user email"; exit 1; }
        git config --global user.name
        git config --global user.email
        echo "Git user set up completed"

    - name: Create assets directory
      run: |
        echo "Creating assets directory"
        mkdir -p assets || { echo "Failed to create assets directory"; exit 1; }
        ls -l
        echo "Assets directory created"

    - name: Download and extract assets
      run: |
        echo "Downloading and extracting assets"
        cd assets || { echo "Failed to change to assets directory"; exit 1; }
        wget -qO- "https://www.dropbox.com/scl/fi/fbuiy99tb218akvy6u9bg/Potato-By-Tyler-Dang.zip?rlkey=1wtfely7oyutriq9qqmihx64b&st=cm1smtvn&dl=1" | tar -xz || { echo "Failed to download or extract assets"; exit 1; }
        echo "Assets downloaded and extracted"
        ls -l
        cd ..

    - name: Debug directory structure
      run: |
        echo "Current directory structure:"
        ls -R

    - name: Commit and push assets
      env:
        GITHUB_TOKEN: ${{ secrets.POTATO_KEY }}
      run: |
        echo "Starting Git operations"
        git add . || { echo "Failed to add files to Git"; exit 1; }
        git status  # Debugging to see what files are staged
        git commit -m "Add assets" || { echo "No changes to commit"; exit 0; }  # Handle no changes scenario without failing
        git push || { echo "Push failed"; exit 1; }
        echo "Git operations completed"
